import { task } from "hardhat/config";
import { TaskArguments } from "hardhat/types";

import { OrigamiMembershipTokenFactory, OrigamiMembershipTokenFactory__factory } from "../src/types";

task("clone:membership-token", "Prints the list of accounts")
  .addParam("contractAddress", "address of the OrigamiMembershipTokenFactory")
  .addParam("admin", "address of the admin for the OrigamiMembershipToken generated by the factory")
  .addParam("name", "name for the OrigamiMembershipToken generated by the factory")
  .addParam("symbol", "symbol for the OrigamiMembershipToken generated by the factory")
  .addParam("baseUri", "baseURI for the OrigamiMembershipToken generated by the factory")
  .setAction(async (args: TaskArguments, { ethers }) => {
    const OMTF__factory: OrigamiMembershipTokenFactory__factory = await ethers.getContractFactory(
      "OrigamiMembershipTokenFactory",
    );
    const OMTF: OrigamiMembershipTokenFactory = await OMTF__factory.attach(args.contractAddress);

    console.log("attached to OrigamiMembershipTokenFactory");
    console.log(await OMTF.DEFAULT_ADMIN_ROLE());
    console.log({ args });

    const tx = await OMTF.createOrigamiMembershipToken(args.admin, args.name, args.symbol, args.baseUri);
    await tx.wait();

    console.log("OrigamiMembershipToken created");

    // console.log({ tx });
    console.log(`OrigamiMembershipToken deployed at ${tx.to}`);
  });
