/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as origamiGovernanceTokenBeforeTransferrerSol from "./OrigamiGovernanceTokenBeforeTransferrer.sol";
export type { origamiGovernanceTokenBeforeTransferrerSol };
export type { OrigamiGovernanceTokenTestVersion } from "./OrigamiGovernanceTokenTestVersion";
export type { OrigamiMembershipTokenBeforeMintEvent } from "./OrigamiMembershipTokenBeforeMintEvent";
export type { OrigamiMembershipTokenTestVersion } from "./OrigamiMembershipTokenTestVersion";
