/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OrigamiGovernanceToken__factory } from "./OrigamiGovernanceToken__factory";
export { OrigamiGovernanceTokenFactory__factory } from "./OrigamiGovernanceTokenFactory__factory";
