/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OrigamiGovernanceToken } from "./OrigamiGovernanceToken";
export type { OrigamiGovernanceTokenBeforeTransferrer } from "./OrigamiGovernanceTokenBeforeTransferrer";
