/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OrigamiGovernanceTokenTestVersion__factory } from "./OrigamiGovernanceTokenTestVersion__factory";
export { OrigamiMembershipTokenTestVersion__factory } from "./OrigamiMembershipTokenTestVersion__factory";
